// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpudmMLzZdsTXER-OIH2O4ffcZdg-kTXs',
    appId: '1:935146891018:web:4cb96f0b2be5836259fcf3',
    messagingSenderId: '935146891018',
    projectId: 'diu-swap',
    authDomain: 'diu-swap.firebaseapp.com',
    storageBucket: 'diu-swap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADimQgKMUcarFLahNKyvAHtkkgEsQcvU8',
    appId: '1:935146891018:android:f17f5495ddd81c2059fcf3',
    messagingSenderId: '935146891018',
    projectId: 'diu-swap',
    storageBucket: 'diu-swap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qY3Wu9ZJw-QH605ZEq-PsEaWEyBWa-w',
    appId: '1:935146891018:ios:c8b6943540b9a66b59fcf3',
    messagingSenderId: '935146891018',
    projectId: 'diu-swap',
    storageBucket: 'diu-swap.firebasestorage.app',
    iosBundleId: 'com.example.projectDiuSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qY3Wu9ZJw-QH605ZEq-PsEaWEyBWa-w',
    appId: '1:935146891018:ios:c8b6943540b9a66b59fcf3',
    messagingSenderId: '935146891018',
    projectId: 'diu-swap',
    storageBucket: 'diu-swap.firebasestorage.app',
    iosBundleId: 'com.example.projectDiuSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpudmMLzZdsTXER-OIH2O4ffcZdg-kTXs',
    appId: '1:935146891018:web:f0cda83220b15b5f59fcf3',
    messagingSenderId: '935146891018',
    projectId: 'diu-swap',
    authDomain: 'diu-swap.firebaseapp.com',
    storageBucket: 'diu-swap.firebasestorage.app',
  );
}
